name: Test PR

on:
  pull_request:
    branches:
      - main
      - dev
      
jobs:

  test-pr:
    name: Test PR
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Install Mono
        shell: bash
        run: sudo apt install mono-devel

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0
        with:
          nuget-version: 6.x
  
      - name: Verify can create NuGet Package
        shell: bash
        run: nuget pack ./nuget/Ceequess.Logo.nuspec
